collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_array.py, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_pg.py, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_tn.py
Ensure `az` can always be used as an alias for `availability_zone` in parameters
fusion_array.py
fusion_pg.py
fusion_tn.py
=> Allow AZ aliases

changelogs/fragments/29_use_env.yaml, plugins/doc_fragments/purestorage.py, plugins/module_utils/fusion.py
Remove `required` for `app_id` and `key_file` so that environmental variables can be used to set these.
fusion.py
=> Fix get_fusion to allow for env variables

changelogs/fragments/44_fix_missing_regions.yaml, plugins/modules/fusion_pg.py, plugins/modules/fusion_tn.py
Adding parameter 'region' to two modules that were missing it. Required parameter to ensure AZ chacks are done in the correct region.
fusion_pg.py
fusion_tn.py
=> Add missing region parameter for PG and TN modules

plugins/modules/fusion_pg.py
This PR fixes fusion_pg docs examples.
It adds region as required parameter in examples section.
fusion_pg
Check docs by using:
```ANSIBLE_LIBRARY=./plugins/modules ansible-doc fusion_pg```
=> Add region as required parameter

plugins/modules/fusion_ts.py
Fix typo in fusion_ts docs. Fix "tenant" word 
https://github.com/Pure-Storage-Ansible/Fusion-Collection/blob/9f38a3675c15376c49c4d610fcce3fb1e40d2167/plugins/modules/fusion_ts.py#L49
fusion_ts
=> Fix typo in fusion_ts docs

changelogs/fragments/PR46_network_interface_groups.yaml, plugins/modules/fusion_info.py
In the module `info` we can gather Fusion information using `network_interface_groups`. It should returns the same information as `nigs`, but instead is rereturns nothing. See code here https://github.com/Pure-Storage-Ansible/Fusion-Collection/blob/cdd8c2e42ad9382ae973dd0d399a58379f2e2a41/plugins/modules/fusion_info.py#L910
I fixed the problem and added information for `network_interface_groups`. 
Module `fusion_info`.
- changelog
```paste below
bugfixes:
- fusion_info - network_interface_groups subset returned nothing. Now it collects the same information
as nigs subset (https://github.com/Pure-Storage-Ansible/Fusion-Collection/pull/46).
deprecated_features:
- fusion_info - nigs subset is deprecated in favor of network_interface_groups and will …
```
=> fix empty network_interface_groups in the module info

plugins/modules/fusion_hap.py
Allowed `:` symbol in IQN pattern because some IQN cases do not match the pattern. For example: `iqn.2052-02.foo.org:01:c5f446d388f4`.
fusion_hap
Now IQN pattern restricts using `:` prefix in unique name. Also it restricts using `' " \s ,` symbols
This pattern refers to RFC [documentation](https://www.rfc-editor.org/rfc/rfc3720#section-3.2.6.3.1)
=> Change regex for ISCSI IQN pattern

changelogs/fragments/PR55_host_access_policy.yaml, plugins/modules/fusion_hap.py
Pr fixes IQN requirement for host access policy deletion. Now only host access policy is needed.
Also bug with uppercase names was fixed.
fusion_hap
Module always checked IQN parameter even in deletion operation. 
Also you could not create name with uppercase letters.
=> Fix host access policy deletion

plugins/module_utils/operations.py, plugins/modules/fusion_array.py, plugins/modules/fusion_az.py, plugins/modules/fusion_hap.py, plugins/modules/fusion_nig.py, plugins/modules/fusion_pg.py, plugins/modules/fusion_pp.py, plugins/modules/fusion_ra.py, plugins/modules/fusion_region.py, plugins/modules/fusion_sc.py, plugins/modules/fusion_se.py, plugins/modules/fusion_ss.py, plugins/modules/fusion_tenant.py, plugins/modules/fusion_ts.py
Some REST API calls (typically most create/update/delete operations) return an Operation ID and the resource is not changed until the Operation finishes. This Operation ID has to be continually polled to find out if it has finished. The collection did not do so, which could cause race conditions in playbook flow. This commit now manually awaits all relevant Operations before the logic proceeds.
(almost) all modules
All of the API call Operations are manually awaited. This is a quick fix that works for now, but may be potentially hard to maintain because it will be prone to miss on code changes and break on updates. Could be solved in the underlying Fusion Python SDK via custom generator extensions or via some custom linting step. Future task.
=> Await all currently called asynchronous API calls

changelogs/fragments/PR62_fix_placements.yaml, plugins/modules/fusion_info.py
The response was empty for the placements parameter. Now it returns the same as placement_groups.Also, marked it as deprecated in favor of placement_groups.
fusion_info
changelog fragment
```paste below
bugfixes:
- fusion_info - placements subset returned nothing. Now it collects the same information
as placement_groups subset (https://github.com/Pure-Storage-Ansible/Fusion-Collection/pull/62).
deprecated_features:
- fusion_info - placements subset is deprecated in favor of placement_groups and will be removed
in the version 1.7.0 (https://github.com/Pure-Storage-Ansible/Fusion-Collection/pull/62).
```
=> fusion_info - fix empty response for the placements parameter.

README.md, plugins/doc_fragments/purestorage.py
Dropping support for python 3.5, 3.6, 3.7 as they are [end-of-life version](https://devguide.python.org/versions/) (or will be in several months in case of Python 3.7). Not supporting these versions doesn't mean the Ansible Collection won't run on the older version, but it will allow the developers to use features of Python 3.6, 3.7 and 3.8. Unless there is a business case for one of the mentioned versions, it's best to drop the support now while the module isn't widely used - now we're starting the development is the best time.
- Python version requirements
Benefits of dropping support for older version:
- enable developers to use features introduces in Python [3.6](https://docs.python.org/3/whatsnew/3.6.html), [3.7](https://docs.python.org/3/whatsnew/3.7.html) and …
=> Change required Python version to 3.8

.gitignore, changelogs/fragments/68_update_error_handling_for_ts_volume.yaml, plugins/module_utils/errors.py, plugins/module_utils/operations.py, plugins/modules/fusion_ts.py, plugins/modules/fusion_volume.py
In general apart from a bit of polishing in the modules themselves this PR adds a global exception handler that intercepts specific REST API-related exceptions, taking care of most failure modes and formatting them into simple and understandable Ansible error messages.
fusion_ts, fusion_volume
The error handler implemented in `module_utils/errors.py` catches two exception types, `fusion.rest.ApiException` and `OperationException` the latter one also added in this PR. It formats these exceptions into a simpler message and passes it via `AnsibleModule.fail_json()` to Ansible. Verbose mode (`ansible-playbook -v` and `ansible-playbook -vv`) still work, first level adding the exception body, second level also a traceback. In general this should take care of most REST API …
=> Improve fusion_ts and fusion_volume errors

changelogs/fragments/70_fix_typo_appiances.yaml, plugins/modules/fusion_info.py
Simple typo fix in one of the output fields, 'appiiances' -> 'appliances'.
fusion_info
None.
=> Fix typo in fusion_info

changelogs/fragments/72_fix_typo_getnifg.yaml, plugins/modules/fusion_se.py
Fixes issue where get_nifg broke because it was still using the previous argument name of provider_subnet, instead of the new name network_interface_group_name
plugins/fusion_se.py
=> get_nifg broken because was still using provider_subnet

changelogs/fragments/73_fix_missing_module_params.yaml, plugins/modules/fusion_pp.py
Fixes issue in fusion_pp where we were missing a required argument when calling parse_minutes, causing create_pp to fail to create protection policy
plugins/fusion_pp.py
=> Minor bugfix to fusion_pp

plugins/modules/fusion_se.py
Bug fix - wrong decision logic about whether the user uses deprecated parameter or not.
fusion_se
=> Bug fix: correct parsing of deprecated parameters

.gitignore, plugins/modules/fusion_volume.py, requirements.txt
This Pull Request introduces a feature which isn't part of the purefusion Python SDK yet. When it is released, this PR can be merged.
Pure Storage Fusion is going to allow users to create/patch a volume with data from another volume or volume snapshot. In order to provide Ansible users the same set of features as the purefusion Python SDK has, we have to introduce this feature for out Ansbile Collection too.
plugins/fusion_volume.py
=> fusion_volume: add option to copy content of a volume or a volume snapshot to a new or already existing volume

plugins/module_utils/getters.py, plugins/modules/fusion_array.py, plugins/modules/fusion_az.py, plugins/modules/fusion_ni.py, plugins/modules/fusion_nig.py, plugins/modules/fusion_pg.py, plugins/modules/fusion_ra.py, plugins/modules/fusion_region.py, plugins/modules/fusion_sc.py, plugins/modules/fusion_se.py, plugins/modules/fusion_ss.py, plugins/modules/fusion_tenant.py, plugins/modules/fusion_tn.py, plugins/modules/fusion_ts.py, plugins/modules/fusion_volume.py
Refactored duplicated getter functions in modules so that they are defined only in one place
- fusion_array.py
- fusion_az.py
- fusion_ni.py
- fusion_nig.py
- fusion_pg.py
- fusion_ra.py
- fusion_region.py
- fusion_sc.py
- fusion_se.py
- fusion_ss.py
- fusion_tenant.py
- fusion_tn.py
- fusion_ts.py
- fusion_volume.py
-  Testing - run playbook for each module
=> Refactor and de-duplicate getters in Ansible modules

changelogs/99_update_protection_policy_retention_description.yaml, plugins/modules/fusion_pp.py
Updated `local_retention` description in Protection Policy module.
`fusion_pp.py`
`Must be between 1MB/s and 512GB/s` is more appropriate to bandwidth limit and it looks like it was copied by mistake (from [here](https://github.com/Pure-Storage-Ansible/Fusion-Collection/blob/master/plugins/modules/fusion_sc.py#L52)), so removing it.
Minimal retention is 10 minutes according to frontdoor validations, so updating it.
=> Update protection policy retention description

changelogs/fragments/103_correct_required_parameters_in_all_modules.yaml, plugins/module_utils/parsing.py, plugins/modules/fusion_array.py, plugins/modules/fusion_hw.py, plugins/modules/fusion_pg.py, plugins/modules/fusion_pp.py, plugins/modules/fusion_sc.py, plugins/modules/fusion_ss.py, tests/integration/targets/fusion_pg/tasks/main.yml, tests/integration/targets/fusion_pp/tasks/main.yml, tests/integration/targets/fusion_sc/tasks/main.yml, tests/integration/targets/fusion_ss/tasks/main.yml, tests/unit/mocks/module_mock.py, tests/unit/modules/test_fusion_array.py
Correct required parameters in all modules. Add possibility to update hardware types in Storage Service.
- _fusion_array_
- _fusion_hw_
- _fusion_pg_
- _fusion_pp_
- _fusion_sc_
- _fusion_ss_
- Several modules in Fusion Ansible collection always required fields which were needed only for resource creation -> fixed
- Module _fusion_sc_ didn't require `storage_service` parameter, but would fail without it -> fixed
- Module _fusion_ss_ didn't allow updating hardware types even though this was supported by Pure Storage Fusion API -> fixed
- ModuleMock class didn't fail if `fail_json` or `fail_on_missing_params` was called, which might cause some test to pass even though they shouldn't -> fixed
- Integration tests and module examples were updated to reflect the changes.
=> Correct required parameters in all modules

.github/workflows/main.yml, tests/sanity/ignore-2.16.txt
Add `stable-2.15` branch to workflows and add `ignore-2.16` file as `ansible-core/devel` moves to `2.16`
=> Add stable/2.15 branch

changelogs/112_unify_hardware_types_key_in_fusion_info.yml, plugins/modules/fusion_info.py
Rename `hardware` to `hardware_types` in fusion_info.py to be the same as a key from `gather_subset` that user specifies.
`fusion_info.py`
Besides key, function `generate_hardware_dict` renamed to be more consistent with other function names.
=> Unify hardware_types key in fusion_info

changelogs/109_unify_storage_classes_key_in_fusion_info.yml, plugins/modules/fusion_info.py, tests/integration/targets/fusion_sc/tasks/main.yml
Rename `storageclass` to `storage_classes` in `fusion_info.py` to be the same as a key from `gather_subset` that user specifies.
`fusion_info.py`
Besides key, function `generate_storageclass_dict` renamed to be more consistent with other function names.
=> Unify storage_classes key in fusion_info

changelogs/fragments/114_fix_fusion_tn_error.yaml, plugins/modules/fusion_tn.py
The `fusion_tn` module doesn't work because it is not supported by `purefusion` Python SDK required by this Ansible Collection. As discussed in previous [PR](https://github.com/Pure-Storage-Ansible/Fusion-Collection/pull/106), the best way is to refactor the module to always return `changed=False` so that existing playbooks do not fail.
- fusion_tn
=> fusion_tn: always return changed=False

plugins/modules/fusion_volume.py
Removing rename example from fusion volume module as rename operation has never been supported and doesn't work.
- fusion_volume
This PR is duplicate of https://github.com/Pure-Storage-Ansible/Fusion-Collection/pull/122
=> fusion_volume: remove rename example

changelogs/129_add_access_token.yml, plugins/doc_fragments/purestorage.py, plugins/module_utils/fusion.py
Add parameter and environment variable for access token. 
Access token can be use as an alternative way of the authentication. 
Module's parameter: `access_token`
Env var: `FUSION_ACCESS_TOKEN`
module_utils/fusion
=> Add access token parameter

changelogs/132_deprecate_unused_parameters_in_hap_module.yml, plugins/modules/fusion_hap.py
Deprecate unused parameters in fusion_hap module.
- fusion_hap
Parameters deprecated in this PR were not used and are not supported by Pure Storage Fusion API.
=> fusion_hap: deprecate unused parameters

changelogs/3289_functests_pp_pg_ra.yml, plugins/modules/fusion_pg.py, plugins/modules/fusion_pp.py, plugins/modules/fusion_ra.py, tests/functional/test_fusion_api_client.py, tests/functional/test_fusion_array.py, tests/functional/test_fusion_az.py, tests/functional/test_fusion_pg.py, tests/functional/test_fusion_pp.py, tests/functional/test_fusion_ra.py, tests/functional/test_fusion_region.py, tests/functional/test_fusion_sc.py, tests/functional/test_fusion_se.py, tests/functional/test_fusion_ss.py, tests/functional/test_fusion_tenant.py, tests/functional/test_fusion_ts.py, tests/functional/utils.py
Implement functional tests for `fusion_pg.py`, `fusion_pp.py` and `fusion_ra.py`.
fusion_ra.py
fusion_pp.py
fusion_pg.py
test_fusion_ra.py
test_fusion_pp.py
test_fusion_pg.py
Following issues were found and fixed during implementation:
- fusion_ra.py: Role name was passed in under `name`, which is really confusing because role assignments also have a name field which seems to be equal to their ID. `name` was deprecated and aliased to `role` instead.
- fusion_pp.py: `local_rpo` accepted only numbers even though it actually contains similar time duration as `local_retention`, which accepts ISO 8601-like strings. `local_rpo` was changed to accept the same input as `local_retention`.
- fusion_pg.py: Placement Group, when created, got array selected by placement engine …
=> Implement functests for pg,pp and ra

changelogs/134_add_cbs_storage_endpoint_support.yml, plugins/modules/fusion_se.py, tests/functional/test_fusion_se.py
Support CBS Storage Endpoint. Deprecation of `endpoint_type` parameter.
- fusion_se
Pure Storage Fusion API support CBS Storage Endpoint. This feature introduces this feature to the Ansbile Collection to maintain parity. `endpoint_type` is deprecated as it is redundant (if user uses iscsi or cbs_iscsi can be found out from which parameter `iscsi` or `cbs_azure_iscsi` they use)
=> Add support for CBS Storage Endpoint

plugins/modules/fusion_info.py, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt
Return type of `complex` was causing an issue and also required sanity ignore files.
Changing to `dict` allows the sanity files to be removed freeing up issues with the new version of `ansible-lint`
fusion_info.py
=> Change return type

changelogs/142_add_missing_none_fields.yml, plugins/modules/fusion_info.py, tests/functional/test_fusion_info.py
Add missing none fields to fusion_info module
Some fields were skipped in dictionaries, now they are presented with None values
Fixed fusion_info tests
fusion_info
=> Add missing none fields

changelogs/143_unify_keys_in_fusion_info.yml, plugins/modules/fusion_info.py, tests/functional/test_fusion_info.py, tests/integration/targets/fusion_az/tasks/main.yml, tests/integration/targets/fusion_hap/tasks/main.yml, tests/integration/targets/fusion_region/tasks/main.yml
Unify keys in fusion_info to improve the user experience.
- fusion_info
minor_changes:
- fusion_info - introduce 'regions' subset option
- fusion_info - introduce 'availability_zones' subset option
- fusion_info - introduce 'host_access_policies' subset option
- fusion_info - introduce 'network_interfaces' subset option
- fusion_info - rename 'zones' dict to 'availability_zones' for consistency
- fusion_info - rename 'hosts' dict to 'host_access_policies' for consistency
- fusion_info - rename 'interfaces' dict to 'network_interfaces' for consistency
- fusion_info - rename 'placements_groups' in default dict to 'placement_groups' for consistency
- fusion_info - rename 'appliances' in default dict to 'arrays' for consistency
deprecated_features:
- fusion_info - …
=> Unify keys in fusion_info

plugins/modules/fusion_ra.py
We sometimes use `api client issuer ID` and `api client key` interchangeably but we should always refer to it as issuer ID for clarity.
`fusion_ra`
=> Improve role-assignment docs

changelogs/fragments/159_fix_protection_policy_local_retention_validation.yaml, plugins/modules/fusion_pp.py
This PR introduces a fix for the minimum value of the protection policy local retention (the correct minimum value is 10, not 1)
`fusion_pp`
=> Fix protection policy local retention validation

plugins/modules/fusion_volume.py, tests/functional/test_fusion_volume.py
fixed bug when task has empty array of host access policies, and state = "absent" and volume exists
fusion_volume.py
=> fix empty hap bug when eradicate
