Pure-Storage-Ansible/Fusion-Collection

.github/workflows/main.yml, collections/ansible_collections/purestorage/fusion/README.md, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_array.py, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_info.py, collections/ansible_collections/purestorage/fusion/tests/sanity/ignore-2.12.txt
Add arrays module and info detail
fusion_info.py
fusion_array.py
=> Add arrays

collections/ansible_collections/purestorage/fusion/README.md, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_info.py, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_pp.py
Add Protection Policies support
fusion_pp.py
fusion_info.py
=> Add Protection Policies

collections/ansible_collections/purestorage/fusion/README.md, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_info.py, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_pg.py, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_volume.py
Add Placement Group support
fusion_info.py
fusion_pg.py
=> Add Placement Groups

collections/ansible_collections/purestorage/fusion/README.md, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_info.py, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_pg.py, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_ts.py
Add Tenant Spaces support
fusion_info.py
fusion_ts.py
=> Add Tenant Spaces

collections/ansible_collections/purestorage/fusion/README.md, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_info.py, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_tn.py, collections/ansible_collections/purestorage/fusion/requirements.txt
Add support for tenant networks
Note that this only supports a single tenant subnet per tenant network and there is no update function for the tenant network or itstenant subnet.
fusion_info.py
fusion_tn.py
=> Add Tenant Networks

collections/ansible_collections/purestorage/fusion/README.md, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_ra.py
Add role assignmentds support
fusion_ra.py
=> Add role assignments

collections/ansible_collections/purestorage/fusion/README.md, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_hw.py
Add hardware tpyes support.
Only creation is currently supported
fusion_hw.py
=> Add hardware types

collections/ansible_collections/purestorage/fusion/README.md, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_az.py
Add AZ support.
Creation only currently.
fusion_az.py
=> Add Availability Zones

collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_info.py
Add follwoing params to info:
- zones
- users
- tenants
fusion_info.py
=> Add new info sections

collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_info.py
Add new info sections:
- Placements
- Roles
fusion_info.py
=> More info sections

collections/ansible_collections/purestorage/fusion/README.md, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_info.py, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_ps.py
Support Provider Subnet support.
Updating a subnet is not yet supported to an SDK issue.
fusion_info.py
fusion_ps.py
=> Add Provider Subnets

collections/ansible_collections/purestorage/fusion/README.md, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_tenant.py
Add Tenants support
fusion_tenant.py
=> Add Tenants

collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_array.py
Fiz bad `az` references
fusion_array.py
=> Fix param name

collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_array.py, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_az.py, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_info.py, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_pp.py, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_ra.py, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_sc.py, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_ss.py, collections/ansible_collections/purestorage/fusion/plugins/modules/fusion_tenant.py, collections/ansible_collections/purestorage/fusion/tests/sanity/ignore-2.13.txt
First drop of most of the GA code
Multiple
=> Part 1 for GA release

CHANGELOG.rst, changelogs/changelog.yaml
Release 1.0.2
Remove unnecessary ANSIBLE_METADATA
Fix Copyright line in modules
Fix documentation with correct formatting macros
=> Release 1.0.2

changelogs/fragments/28_any_region.yaml, plugins/modules/fusion_az.py
Remove the requirement to have preset regions
fusion_az.py
=> Allow any region

README.md, galaxy.yml, plugins/modules/fusion_region.py, requirements.txt
Add support for creation and deletion of regions.
Region `display_name` can also be modified.
Associated docs changed.
fusion_region.py
=> Add support for regions management

changelogs/fragments/34_add_delete_ss.yaml, plugins/modules/fusion_ss.py
Add `state: absent` option for storage services
fusion_ss.py
=> Add SS deletion option

changelogs/fragments/33_add_delete_sc.yaml, plugins/modules/fusion_sc.py
Add `state: absent` option for storage classes
fusion_sc.py
=> Add SC deletion option

changelogs/fragments/32_add_delete_pp.yaml, plugins/modules/fusion_pp.py
Add `state: absent` option for protection policies
fusion_pp.py
=> Add PP deletion option

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/27_review_fixes.yaml, changelogs/fragments/28_any_region.yaml, changelogs/fragments/29_use_env.yaml, changelogs/fragments/31_add_delete_az.yaml, changelogs/fragments/32_add_delete_pp.yaml, changelogs/fragments/33_add_delete_sc.yaml, changelogs/fragments/34_add_delete_ss.yaml
=> Release 1.1.0

plugins/modules/fusion_az.py, plugins/modules/fusion_volume.py
Remove unnecessary variables.
Not visible to consumers.
fusion_az.py
fusion_volume.py
=> Remove unused variables

.github/workflows/main.yml, plugins/modules/fusion_ss.py, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt
=> Add 2.14 to CI tests

plugins/modules/fusion_info.py
Emergency fixes
fusion_info.py
=> Emergency fix for info based on undocumented SDK changes

changelogs/fragments/41_add_api_client.yaml, plugins/modules/fusion_info.py
Add API Client info.
Add new subset of `api_clients`
fusion_info.py
=> Add API Client info

README.md, changelogs/fragments/46_deprecate fusion_tn.yaml, galaxy.yml, meta/runtime.yml, plugins/doc_fragments/purestorage.py, plugins/modules/fusion_region.py, plugins/modules/fusion_se.py
Tenant Network concept is being remodeled in the underlying Python SDK and functionality is being moved to Storage Endpoints + Network Interface Groups. The PR mirrors these changes.
Introduces Storage Endpoints (module fusion_se) and deprecates Tenant Networks (module fusion_tn).
fusion_se, fusion_tn
This mirrors changes in underlying Python SDK that lives in PyPI 'purefusion' package.
=> Introduce Storage Endpoints

plugins/module_utils/parsing.py, plugins/modules/fusion_pp.py, plugins/modules/fusion_sc.py, plugins/modules/fusion_volume.py, tests/unit/module_utils/parsing.py
Unifies parsing routines related to metric suffixes (-K, -M, ...) and fixes corner cases of some other parsing routines (related to time periods).
fusion_sc, fusion_pp
=> Unify number parsing routines

plugins/module_utils/fusion.py
API endpoints are hard coded in pure fusion python SDK, this change make the settings configurable
plugin/module_utils/fusion.py
=> Make API endpoints configurable

plugins/modules/fusion_az.py, plugins/modules/fusion_hap.py, plugins/modules/fusion_nig.py, plugins/modules/fusion_pg.py, plugins/modules/fusion_pp.py, plugins/modules/fusion_ra.py, plugins/modules/fusion_region.py, plugins/modules/fusion_sc.py, plugins/modules/fusion_se.py, plugins/modules/fusion_ss.py, plugins/modules/fusion_tenant.py, plugins/modules/fusion_ts.py
Fixes previous await_operation() deployment version which sometimes passed entire Operation into await instead of only the Operation ID.
most modules
=> Fix asynchronous Operation await

README.md, changelogs/fragments/63_update_resource_patching.yaml, plugins/module_utils/networking.py, plugins/modules/fusion_array.py, plugins/modules/fusion_nig.py, plugins/modules/fusion_pg.py, plugins/modules/fusion_sc.py, plugins/modules/fusion_se.py, plugins/modules/fusion_ss.py, plugins/modules/fusion_ts.py, plugins/modules/fusion_volume.py, requirements.txt, tests/unit/module_utils/networking.py, tests/unit/networking.py
Updates modules to be able to update all properties of all managed resources the underlying Python SDK can. Also removes dependency on external `netaddr` package.
fusion_array
fusion_nig
fusion_pg
fusion_se
fusion_ss
fusion_ts
fusion_volume
The `netaddr` package is replaced by `ipaddress` package instead, which is part of Python standard library for all supported versions.
=> Improve updating resources to parity with SDK

requirements.txt
Specifying package versions in the requirements file is not only a best practice but can prevent many future bugs.
=> Specify package versions in requirements.txt

plugins/modules/fusion_array.py, plugins/modules/fusion_sc.py
Remove unused imports as required by new Ansible pylint test
fusion_array.py
fusion_sc.py
=> Remove unused imports

plugins/modules/fusion_array.py, plugins/modules/fusion_az.py
Improve error handling for array and az modules
fusion_az
fusion_array
=> Improve error handling for array and az modules

plugins/modules/fusion_ra.py, plugins/modules/fusion_region.py
fusion_ra, fusion_region: update error handling so it match other modules
fusion_ra, fusion_region
=> fusion_ra, fusion_region: update error handling so it match other modules

plugins/module_utils/errors.py, plugins/module_utils/operations.py, plugins/modules/fusion_array.py, plugins/modules/fusion_az.py, plugins/modules/fusion_hap.py, plugins/modules/fusion_nig.py, plugins/modules/fusion_pg.py, plugins/modules/fusion_pp.py, plugins/modules/fusion_ra.py, plugins/modules/fusion_region.py, plugins/modules/fusion_sc.py, plugins/modules/fusion_se.py, plugins/modules/fusion_ss.py, plugins/modules/fusion_tenant.py, plugins/modules/fusion_ts.py, plugins/modules/fusion_volume.py
This PR adds Operation name to urllib3 HTTPError in await_operation()
- 
errors
operations
=> Attach operation name to HTTPError

changelogs/fragments/71_fix_few_missing_format_params.yaml, plugins/modules/fusion_nig.py, plugins/modules/fusion_se.py, plugins/modules/fusion_ts.py
Simple fix that fills in format missing parameters in a few error messages.
fusion_nig
fusion_ts
fusion_se
=> Fix missing format params

plugins/module_utils/errors.py
=> Fix OperationException

README.md, plugins/modules/fusion_ni.py
Introducing new module fusion_ni for managing network interfaces.
fusion_ni
In order to provide users parity with purefusion Python SDK, the Network Interfaces module is needed.
=> Introduce Network Interfaces

plugins/module_utils/errors.py, plugins/module_utils/operations.py, plugins/modules/fusion_array.py, plugins/modules/fusion_az.py, plugins/modules/fusion_hap.py, plugins/modules/fusion_nig.py, plugins/modules/fusion_pg.py, plugins/modules/fusion_pp.py, plugins/modules/fusion_ra.py, plugins/modules/fusion_region.py, plugins/modules/fusion_sc.py, plugins/modules/fusion_se.py, plugins/modules/fusion_ss.py, plugins/modules/fusion_tenant.py, plugins/modules/fusion_ts.py, plugins/modules/fusion_volume.py, tests/unit/mocks/array_mock.py, tests/unit/mocks/exceptions_mock.py, tests/unit/mocks/module_mock.py, tests/unit/mocks/operation_mock.py, tests/unit/module_utils/test_operations.py, tests/unit/modules/test_fusion_array.py, tests/unit/modules/test_fusion_az.py
Adds:
1. Mocks
2. operations tests
3. fusion_az tests
4. fusion_array tests
5. Deletes unused parameter in await_operation function
fusion_az 
fusion_array
=> Unit tests

plugins/modules/fusion_ni.py, plugins/modules/fusion_se.py
Fixes extra invalid parameter module in await_operation function in fusion_ni.py and fusion_se.py
fusion_ni.py
fusion_se.py
=> Fix for invalid parameter to await_operation function

plugins/modules/fusion_hap.py, plugins/modules/fusion_pp.py, plugins/modules/fusion_ss.py
Fixing examples in module description
- fusion_hap.py
- fusion_pp.py
- fusion_ss.py
=> Fix typos and errors in module examples

.github/workflows/main.yml
Add Unit Tests to the GitHub workflow, so they are run automatically before merging any Pull Request.
- GitHub Workflow
=> Run unit tests in main workflow

plugins/modules/fusion_ss.py
This is not actually supported by backend and was merged in error.
fusion_ss
=> Do not try to update hardware types for storage service

changelogs/fragments/108_add_missing_hap_personality.yaml, plugins/modules/fusion_hap.py
Adds missing "windows" HAP personality type 
fusion_hap
=> Add missing HAP personality type

.github/workflows/create-release.yaml, CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/102_set_hap_display_name_default_value.yaml, changelogs/fragments/103_correct_required_parameters_in_all_modules.yaml, changelogs/fragments/108_add_missing_hap_personality.yaml, changelogs/fragments/114_fix_fusion_tn_error.yaml, changelogs/fragments/1483_allow_to_unset_protection_policy.yaml, changelogs/fragments/1538_improve_missing_python_deps_error.yaml, galaxy.yml, playbooks/simple/setup_infrastructure.yml
New Release 1.4.2
- New Release
=> Release 1.4.2

.github/workflows/create-release.yaml
=> Fix release_version variable

plugins/modules/fusion_api_client.py, tests/functional/test_fusion_api_client.py
Add functional tests for fusion_api_client.
- tests
Add functional tests for fusion_api_client. Refactoring fusion_api_client file a bit.
=> Add functional tests for fusion_api_client.

changelogs/127_change_logic_of_fusion_api_host.yml, plugins/module_utils/fusion.py
Updated base path for ansible collection
plugins
=> updated base path for ansible

plugins/modules/fusion_hap.py, plugins/modules/fusion_nig.py, tests/functional/test_fusion_az.py, tests/functional/test_fusion_hap.py, tests/functional/test_fusion_hw.py, tests/functional/test_fusion_nig.py
Add functional tests.
- tests
Adding functional tests for fusion_hap, fusion_hw, fusion_nig.
=> Adding functional tests for fusion_hap, fusion_hw, fusion_nig.

plugins/module_utils/parsing.py, plugins/modules/fusion_volume.py, tests/functional/test_fusion_volume.py, tests/functional/utils.py, tests/unit/module_utils/test_parsing.py
Added functional tests for fusion_volume
tests
=> add fusion_volume functional tests

.github/workflows/ansible-lint.yaml, .github/workflows/create-release.yaml, .github/workflows/main.yml, changelogs/fragments/156_allow_leading_zeros.yaml, plugins/module_utils/parsing.py, tests/unit/module_utils/test_parsing.py
Allow leading zeros in duration strings.
- fusion_pp
=> Allow leading zeros in duration strings

plugins/module_utils/errors.py, plugins/module_utils/prerequisites.py
Fix lint errors found out during the latest release.
- module_utils/prerequisites.py
- module_utils/errors.py
=> Fix lint errors

changelogs/fragments/151_create_volume_using_existing_volume_or_snapshot.yaml, plugins/modules/fusion_volume.py, tests/functional/test_fusion_volume.py
Allow creating a new volume from already existing volume or volume snapshot
- fusion_volume
=> Allow creating a new volume from already existing volume or volume snapshot

.github/workflows/ansible-lint.yaml, .github/workflows/black.yaml, .github/workflows/create-release.yaml, .github/workflows/main.yml, .github/workflows/rh_automation_hub_token_keep_alive.yml, .github/workflows/stale.yml
Fix CI failures caused by truthy issues
=> Truthy fixes
